/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `image`;

CREATE TABLE `image` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `data` BLOB NOT NULL,
  `type` TEXT NOT NULL)
 ENGINE=InnoDB;

